name = "yt-live-notify"
main = "worker.js"
compatibility_date = "2026-01-01"

[vars]
GH_REPO = "Garfiwld/YT-LiveRec"

[triggers]
crons = ["*/10 * * * *"]

[[kv_namespaces]]
binding = "CHANNELS_KV"
id = "01353302e6444a12916ad10b493ebf26"
